name: build
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        with:
          node-version: '18'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
          scope: '@gcoreplus'
      - run: |
          yarn
          yarn run build
          yarn run test
          yarn run publish:npm
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
